In [63]:
# dataset: https://github.com/mwaskom/seaborn-data/blob/master/exercise.csv

import pandas as pd

# Open a file

data = pd.read_csv(
    "exercise.csv",
    sep=",",
    header="infer",
    index_col=0,
    encoding="utf-8"
)

# In jupyter notebook, dataframes are prettier without using print()
data

    id     diet  pulse    time     kind
0    1  low fat     85   1 min     rest
1    1  low fat     85  15 min     rest
2    1  low fat     88  30 min     rest
3    2  low fat     90   1 min     rest
4    2  low fat     92  15 min     rest
..  ..      ...    ...     ...      ...
85  29   no fat    135  15 min  running
86  29   no fat    130  30 min  running
87  30   no fat     99   1 min  running
88  30   no fat    111  15 min  running
89  30   no fat    150  30 min  running

[90 rows x 5 columns]

In [64]:
# Access elements by id

data.head(1)
data.tail(1) 

data.loc[0]
data.loc[0:10]

    id     diet  pulse    time  kind
0    1  low fat     85   1 min  rest
1    1  low fat     85  15 min  rest
2    1  low fat     88  30 min  rest
3    2  low fat     90   1 min  rest
4    2  low fat     92  15 min  rest
5    2  low fat     93  30 min  rest
6    3  low fat     97   1 min  rest
7    3  low fat     97  15 min  rest
8    3  low fat     94  30 min  rest
9    4  low fat     80   1 min  rest
10   4  low fat     82  15 min  rest

In [65]:
# Looping over rows

# Will only show the column names
for i in data:
    print(i)

# Correct loop over rows with iterrows()
for index,row in data.iterrows():
    print(row["id"],row["kind"]) # you can also just do "print(row)"

id
diet
pulse
time
kind
1 rest
1 rest
1 rest
2 rest
2 rest
2 rest
3 rest
3 rest
3 rest
4 rest
4 rest
4 rest
5 rest
5 rest
5 rest
6 rest
6 rest
6 rest
7 rest
7 rest
7 rest
8 rest
8 rest
8 rest
9 rest
9 rest
9 rest
10 rest
10 rest
10 rest
11 walking
11 walking
11 walking
12 walking
12 walking
12 walking
13 walking
13 walking
13 walking
14 walking
14 walking
14 walking
15 walking
15 walking
15 walking
16 walking
16 walking
16 walking
17 walking
17 walking
17 walking
18 walking
18 walking
18 walking
19 walking
19 walking
19 walking
20 walking
20 walking
20 walking
21 running
21 running
21 running
22 running
22 running
22 running
23 running
23 running
23 running
24 running
24 running
24 running
25 running
25 running
25 running
26 running
26 running
26 running
27 running
27 running
27 running
28 running
28 running
28 running
29 running
29 running
29 running
30 running
30 running
30 running

In [66]:
# Looping over columns

data.columns # show the columns
data.columns = ["id","diet","pulse","time","kind"] # change the column names

for i in data["pulse"]:
    print(i)
    
for i,pulse in enumerate(data["pulse"]):
    print(pulse,data["kind"][i])

85
85
88
90
92
93
97
97
94
80
82
83
91
92
91
83
83
84
87
88
90
92
94
95
97
99
96
100
97
100
86
86
84
93
103
104
90
92
93
95
96
100
89
96
95
84
86
89
103
109
90
92
96
101
97
98
100
102
104
103
93
98
110
98
104
112
98
105
99
87
132
120
94
110
116
95
126
143
100
126
140
103
124
140
94
135
130
99
111
150
85 rest
85 rest
88 rest
90 rest
92 rest
93 rest
97 rest
97 rest
94 rest
80 rest
82 rest
83 rest
91 rest
92 rest
91 rest
83 rest
83 rest
84 rest
87 rest
88 rest
90 rest
92 rest
94 rest
95 rest
97 rest
99 rest
96 rest
100 rest
97 rest
100 rest
86 walking
86 walking
84 walking
93 walking
103 walking
104 walking
90 walking
92 walking
93 walking
95 walking
96 walking
100 walking
89 walking
96 walking
95 walking
84 walking
86 walking
89 walking
103 walking
109 walking
90 walking
92 walking
96 walking
101 walking
97 walking
98 walking
100 walking
102 walking
104 walking
103 walking
93 running
98 running
110 running
98 running
104 running
112 running
98 running
105 running
99 running
87 running
132 running
120 running
94 running
110 running
116 running
95 running
126 running
143 running
100 running
126 running
140 running
103 running
124 running
140 running
94 running
135 running
130 running
99 running
111 running
150 running

In [67]:
# Add a row

data = pd.concat(
    [
        pd.DataFrame([[1,"test",0,"15 min","test"]], columns=data.columns),
        data
    ],
    ignore_index=True
)

data

    id     diet  pulse    time     kind
0    1     test      0  15 min     test
1    1  low fat     85   1 min     rest
2    1  low fat     85  15 min     rest
3    1  low fat     88  30 min     rest
4    2  low fat     90   1 min     rest
..  ..      ...    ...     ...      ...
86  29   no fat    135  15 min  running
87  29   no fat    130  30 min  running
88  30   no fat     99   1 min  running
89  30   no fat    111  15 min  running
90  30   no fat    150  30 min  running

[91 rows x 5 columns]

In [68]:
# Add a column

new_column = []

for i in range(len(data)):
    new_column.append(f"col number {i}")
    
data["description"] = new_column

data

    id     diet  pulse    time     kind    description
0    1     test      0  15 min     test   col number 0
1    1  low fat     85   1 min     rest   col number 1
2    1  low fat     85  15 min     rest   col number 2
3    1  low fat     88  30 min     rest   col number 3
4    2  low fat     90   1 min     rest   col number 4
..  ..      ...    ...     ...      ...            ...
86  29   no fat    135  15 min  running  col number 86
87  29   no fat    130  30 min  running  col number 87
88  30   no fat     99   1 min  running  col number 88
89  30   no fat    111  15 min  running  col number 89
90  30   no fat    150  30 min  running  col number 90

[91 rows x 6 columns]

In [69]:
# Modify a cell value

data.loc[0,"description"] = "ITS A TRAP"

data.head()

   id     diet  pulse    time  kind   description
0   1     test      0  15 min  test    ITS A TRAP
1   1  low fat     85   1 min  rest  col number 1
2   1  low fat     85  15 min  rest  col number 2
3   1  low fat     88  30 min  rest  col number 3
4   2  low fat     90   1 min  rest  col number 4

In [70]:
# Modify every cell value in a column

for i,value in enumerate(data["description"]):
    data.loc[i,"description"] = value.replace("number","")
    
data

    id     diet  pulse    time     kind description
0    1     test      0  15 min     test  ITS A TRAP
1    1  low fat     85   1 min     rest      col  1
2    1  low fat     85  15 min     rest      col  2
3    1  low fat     88  30 min     rest      col  3
4    2  low fat     90   1 min     rest      col  4
..  ..      ...    ...     ...      ...         ...
86  29   no fat    135  15 min  running     col  86
87  29   no fat    130  30 min  running     col  87
88  30   no fat     99   1 min  running     col  88
89  30   no fat    111  15 min  running     col  89
90  30   no fat    150  30 min  running     col  90

[91 rows x 6 columns]

In [71]:
# Delete a row

data = data.drop(0)
data = data.drop([1,2,3])

data

    id     diet  pulse    time     kind description
4    2  low fat     90   1 min     rest      col  4
5    2  low fat     92  15 min     rest      col  5
6    2  low fat     93  30 min     rest      col  6
7    3  low fat     97   1 min     rest      col  7
8    3  low fat     97  15 min     rest      col  8
..  ..      ...    ...     ...      ...         ...
86  29   no fat    135  15 min  running     col  86
87  29   no fat    130  30 min  running     col  87
88  30   no fat     99   1 min  running     col  88
89  30   no fat    111  15 min  running     col  89
90  30   no fat    150  30 min  running     col  90

[87 rows x 6 columns]

In [72]:
# Delete a column

data = data.drop(columns=["kind"])

data

    id     diet  pulse    time description
4    2  low fat     90   1 min      col  4
5    2  low fat     92  15 min      col  5
6    2  low fat     93  30 min      col  6
7    3  low fat     97   1 min      col  7
8    3  low fat     97  15 min      col  8
..  ..      ...    ...     ...         ...
86  29   no fat    135  15 min     col  86
87  29   no fat    130  30 min     col  87
88  30   no fat     99   1 min     col  88
89  30   no fat    111  15 min     col  89
90  30   no fat    150  30 min     col  90

[87 rows x 5 columns]

In [74]:
# Save a file

data.to_csv(
    "exercise_v2.csv",
    sep=",",
    header=True,
    index=True,
    encoding="utf-8"
)